### ISSUE TITLE
ALE crashes everywhere.

### ISSUE THREAD

**Issue by bbjimmy** [czeidler/ALEditor#1]
Ale chashes on every mouse click, on file load, on file save, etc. There is no action that does not crash the program on   haiku hrev49176.  This happens with the haikudepot version, and after downloading and compiling the source.

**Comment by czeidler** [comment]
Sounds there is something serious wrong :) Maybe some ABI change or architecture miss match? Do you have a stack trace?

**Comment by bbjimmy** [comment]
debug report:

Debug information for team /boot/home/Desktop/ALEditor (18457):
CPU(s): 1x Intel Pentium 4
Memory: 1.49 GiB total, 1.09 GiB used
Haiku revision: hrev49176 May 17 2015 02:46:37 (BePC)

Active Threads:
    thread 18457: ALEditor (main)
    thread 18468: w>ALEditor: Save 
    thread 18471: w>ALEditor: Open 
    thread 18473: w>Properties 
    thread 18475: team 18457 debug task 
    thread 18465: w>Layout Playground 
        state: Call (Deleting a BLayout that still has items. Subclass hooks will not be called)

```
    Frame       IP          Function Name
    -----------------------------------------------
    00000000    0x60a43112  commpage_syscall + 0x2 
        Disassembly:
            commpage_syscall:
            0x60a43110:             89e1  mov %esp, %ecx
            0x60a43112:             0f34  sysenter  <--

        Frame memory:

    0x70cd2488  0xa16f89    debugger + 0x39 
    0x70cd24c0  0x24dfa33   _._7BLayout + 0x63 
    0x70cd24f0  0x249f34e   _._15BAbstractLayout + 0x4e 
    0x70cd2520  0x1240376   _._Q24BALM10BALMLayout + 0x20a 
    0x70cd2570  0x20d4b71   BALM::EditWindow::_SetTabAreaContent(BView*) + 0xad 
    0x70cd25e0  0x20d5349   BALM::EditWindow::UpdateEditWindow() + 0x59 
    0x70cd2610  0x20b1ef7   BALM::BALMEditor::UpdateEditWindow() + 0x2b 
    0x70cd2660  0x20b5c08   BALM::LayoutEditView::MouseUp(BPoint) + 0x130 
    0x70cd2840  0x2559fe7   BWindow::DispatchMessage(BMessage*, BHandler*) + 0xdf7 
    0x70cd28a0  0x255e756   BWindow::task_looper() + 0x28e 
    0x70cd28d0  0x247bc05   BLooper::_task0_(void*) + 0x3d 
    0x70cd28f8  0xa1e049    thread_entry + 0x21 
    00000000    0x60a43250  commpage_thread_exit + 0 

    Registers:
          eip:  0x60a43114
          esp:  0x70cd244c
          ebp:  0x70cd2488
          eax:  0x000000de
          ebx:  0x00ac3738
          ecx:  0x70cd244c
          edx:  0x60a43114
          esi:  0x026140c0
          edi:  0x00000000
           cs:  0x001b
           ds:  0x0023
           es:  0x0023
           fs:  0x0063
           gs:  0x0023
           ss:  0x0023
          st0:  nan
          st1:  nan
          st2:  nan
          st3:  1
          st4:  0
          st5:  0
          st6:  0
          st7:  -2
          mm0:  {0, 0, 0, 0}
          mm1:  {0xf29, 0, 0, 0}
          mm2:  {0xe2f0, 0, 0, 0}
          mm3:  {0, 0, 0, 0x8000}
          mm4:  {0, 0, 0, 0}
          mm5:  {0, 0, 0, 0}
          mm6:  {0, 0, 0, 0}
          mm7:  {0, 0, 0, 0x8000}
         xmm0:  {0, 0, 0, 0, 0, 0, 0, 0}
         xmm1:  {0, 0, 0, 0, 0, 0, 0, 0}
         xmm2:  {0, 0, 0, 0, 0, 0, 0, 0}
         xmm3:  {0, 0, 0, 0, 0, 0, 0, 0}
         xmm4:  {0, 0, 0, 0, 0, 0, 0, 0}
         xmm5:  {0, 0, 0, 0, 0, 0, 0, 0}
         xmm6:  {0, 0, 0, 0, 0, 0, 0, 0}
         xmm7:  {0, 0, 0, 0, 0, 0, 0, 0}
```

Loaded Images:
    ID      Text Base   Text End    Data Base   Data End    Type    Name
    --------------------------------------------------------------------------------
    36005   0x009ed000  0x00aba000  0x00aba000  0x00b05000  lib     /boot/system/lib/libroot.so
    36010   0x00b35000  0x00b3f000  0x00b3f000  0x00b43000  lib     /boot/system/lib/libiculx.so.55.1
    36009   0x00b61000  0x00bb4000  0x00bb4000  0x00bbe000  lib     /boot/system/lib/libicule.so.55.1
    36013   0x00e3e000  0x00e57000  0x00e57000  0x00e58000  lib     /boot/system/lib/libz.so.1.2.8
    36001   0x01229000  0x01258000  0x01258000  0x01262000  lib     /boot/system/lib/libalm.so
    36007   0x0129a000  0x014fe000  0x014fe000  0x01560000  lib     /boot/system/lib/libicui18n.so.55.1
    36011   0x015ca000  0x01602000  0x01602000  0x0163a000  lib     /boot/system/lib/libicutu.so.55.1
    35999   0x01646000  0x0164a000  0x0164a000  0x0164c000  app     /boot/home/Desktop/ALEditor
    35998   0x01673000  0x0168f000  0x0168f000  0x01692000  lib     /boot/system/runtime_loader
    36012   0x01b87000  0x01ce0000  0x01ce0000  0x01d11000  lib     /boot/system/lib/libicuuc.so.55.1
    36008   0x01eef000  0x01ef8000  0x01ef8000  0x01ef9000  lib     /boot/system/lib/libicuio.so.55.1
    36004   0x01f48000  0x01f79000  0x01f79000  0x01f87000  lib     /boot/system/lib/libstdc++.r4.so
    36003   0x01fff000  0x020ee000  0x020ee000  0x02130000  lib     /boot/system/lib/libale.so
    36014   0x02130000  0x02144000  0x02144000  0x02149000  lib     /boot/system/lib/libtranslation.so
    36002   0x02161000  0x0230c000  0x0230c000  0x0236b000  lib     /boot/system/lib/libtracker.so
    36000   0x0237b000  0x02622000  0x02622000  0x026ae000  lib     /boot/system/lib/libbe.so
    36015   0x0275c000  0x02853000  0x02853000  0x02856000  lib     /boot/system/lib/libtextencoding.so
    36006   0x02bca000  0x04480000  0x04480000  0x04481000  lib     /boot/system/lib/libicudata.so.55.1
    35997   0x60a43000  0x60a4b000  0x00000000  0x00000000  system  commpage

Areas:
    ID      Base        End         Size (KiB)  Protection  Locking         Name
    --------------------------------------------------------------------------------
    268019  0x00113000  0x00123000          64  rw-         full            rld heap
    268018  0x001b5000  0x001bd000          32  rw-         full            rld heap
    267962  0x00218000  0x00219000           4  rw-S        full            _rld_debug_
    267961  0x00513000  0x00523000          64  rw-         full            rld heap
    267989  0x009ed000  0x00aba000         820  r-x         full            libroot.so_seg0ro
    267990  0x00aba000  0x00acd000          76  rw-         full            libroot.so_seg1rw
    267991  0x00acd000  0x00b05000         224  rw-         full            libroot.so_seg2rw
    268001  0x00b35000  0x00b3f000          40  r-x         full            libiculx.so.55.1_seg0ro
    268002  0x00b3f000  0x00b43000          16  rw-         full            libiculx.so.55.1_seg1rw
    267999  0x00b61000  0x00bb4000         332  r-x         full            libicule.so.55.1_seg0ro
    268000  0x00bb4000  0x00bbe000          40  rw-         full            libicule.so.55.1_seg1rw
    268009  0x00e3e000  0x00e57000         100  r-x         full            libz.so.1.2.8_seg0ro
    268010  0x00e57000  0x00e58000           4  rw-         full            libz.so.1.2.8_seg1rw
    267975  0x01229000  0x01258000         188  r-x         full            libalm.so_seg0ro
    267976  0x01258000  0x01261000          36  rw-         full            libalm.so_seg1rw
    267977  0x01261000  0x01262000           4  rw-         full            libalm.so_seg2rw
    267994  0x0129a000  0x014fe000        2448  r-x         full            libicui18n.so.55.1_seg0ro
    267995  0x014fe000  0x0155f000         388  rw-         full            libicui18n.so.55.1_seg1rw
    267996  0x0155f000  0x01560000           4  rw-         full            libicui18n.so.55.1_seg2rw
    268003  0x015ca000  0x01602000         224  r-x         full            libicutu.so.55.1_seg0ro
    268004  0x01602000  0x01608000          24  rw-         full            libicutu.so.55.1_seg1rw
    268005  0x01608000  0x0163a000         200  rw-         full            libicutu.so.55.1_seg2rw
    267963  0x01646000  0x0164a000          16  r-x         full            ALEditor_seg0ro
    267964  0x0164a000  0x0164b000           4  rw-         full            ALEditor_seg1rw
    267969  0x0164b000  0x0164c000           4  rw-         full            ALEditor_seg2rw
    267958  0x01673000  0x0168f000         112  r-x         full            runtime_loader_seg0ro
    267959  0x0168f000  0x01691000           8  rw-         full            runtime_loader_seg1rw
    267960  0x01691000  0x01692000           4  rw-         full            runtime_loader_bss1
    268006  0x01b87000  0x01ce0000        1380  r-x         full            libicuuc.so.55.1_seg0ro
    268007  0x01ce0000  0x01d0f000         188  rw-         full            libicuuc.so.55.1_seg1rw
    268008  0x01d0f000  0x01d11000           8  rw-         full            libicuuc.so.55.1_seg2rw
    267997  0x01eef000  0x01ef8000          36  r-x         full            libicuio.so.55.1_seg0ro
    267998  0x01ef8000  0x01ef9000           4  rw-         full            libicuio.so.55.1_seg1rw
    267986  0x01f48000  0x01f79000         196  r-x         full            libstdc++.r4.so_seg0ro
    267987  0x01f79000  0x01f84000          44  rw-         full            libstdc++.r4.so_seg1rw
    267988  0x01f84000  0x01f87000          12  rw-         full            libstdc++.r4.so_seg2rw
    267983  0x01fff000  0x020ee000         956  r-x         full            libale.so_seg0ro
    267984  0x020ee000  0x0212f000         260  rw-         full            libale.so_seg1rw
    267985  0x0212f000  0x02130000           4  rw-         full            libale.so_seg2rw
    268011  0x02130000  0x02144000          80  r-x         full            libtranslation.so_seg0ro
    268012  0x02144000  0x02148000          16  rw-         full            libtranslation.so_seg1rw
    268013  0x02148000  0x02149000           4  rw-         full            libtranslation.so_seg2rw
    267978  0x02161000  0x0230c000        1708  r-x         full            libtracker.so_seg0ro
    267979  0x0230c000  0x02369000         372  rw-         full            libtracker.so_seg1rw
    267980  0x02369000  0x0236b000           8  rw-         full            libtracker.so_seg2rw
    267970  0x0237b000  0x02622000        2716  r-x         full            libbe.so_seg0ro
    267971  0x02622000  0x026ad000         556  rw-         full            libbe.so_seg1rw
    267972  0x026ad000  0x026ae000           4  rw-         full            libbe.so_seg2rw
    268014  0x0275c000  0x02853000         988  r-x         full            libtextencoding.so_seg0ro
    268017  0x02853000  0x02856000          12  rw-         full            libtextencoding.so_seg1rw
    267992  0x02bca000  0x04480000       25304  r-x         full            libicudata.so.55.1_seg0ro
    267993  0x04480000  0x04481000           4  rw-         full            libicudata.so.55.1_seg1rw
    268020  0x18583000  0x18793000        2112  rw-         full            heap
    267957  0x60a43000  0x60a4b000          32  r-xSk       full            commpage
    267954  0x61f67000  0x61f6b000          16  rw-         full            user area
    268027  0x61fe7000  0x61fe8000           4  rw-S        full            server_memory
    268039  0x70a0c000  0x70a51000         276  rw-s        full            w>TrackerWindow_18468_stack
    268033  0x70c8f000  0x70cd4000         276  rw-s        full            w>Layout Playground_18465_stack
    268045  0x713b4000  0x713f9000         276  rw-s        full            w>TrackerWindow_18471_stack
    267956  0x719e7000  0x729e8000       16388  rw-s        full            ALEditor_18457_stack
    268029  0x729e8000  0x72a08000         128  rw-S        full            server_memory
    268049  0x7b0a1000  0x7b0e6000         276  rw-s        full            w>Properties_18473_stack

Protection Flags: r - read, w - write, x - execute, s - stack, o - overcommit, c - cloneable, S - shared, k - kernel

Semaphores:
    ID      Count   Last Holder Name
    ------------------------------------------------------------
    2990492     0         -1120 token space
    2990505     0             0 Light Lock
    2990956     0         -1192 some BLocker
    2991135     0         -8175 virtual directory manager
    2991686     0         18471 clipboard
    2991735     0         -1120 some BBlockCache lock
    2991745     0          1192 some BLocker
    2991746     0         -1120 BMessageQueue Lock
    2991749     0         -1192 BLooperList lock
    2991762     0          1120 Light Lock
    2991763     0         -1120 some BLocker
    2991771     0          1120 some BLocker
    2991772     0          1120 screen list
    2991773     0         -1192 undo
    2991778     0          1120 BMessageQueue Lock
    2991780     0         -1120 BMessageQueue Lock
    2991788     0          1192 BMessageQueue Lock
    2991791     0         -8297 LocaleRosterData
    2991792     0         -1120 AppServerLink_sLock
    2991800     0          1120 width buffer
    2991812     0         -1120 BMessageQueue Lock
    2991813     0          1120 some BLocker
    2991814     0         -8306 Catalog
    2991815     0         -1120 some BLocker
    2991829     0          1120 Catalog
    2991833     0          1120 AppLooperPort
    2991838     0          1120 some BLocker
    2991839     0         -8312 Catalog
    2991842     0          1120 some BLocker
    2991845     0         18469 TrackerWindow
    2991854     0          1120 PeriodicUpdatePoses
    2991857     0         17997 some BLocker
    2991859     0         -1120 tool tip manager
    2991863     0         -1120 Tracker node icon cache
    2991873     0         18472 TrackerWindow
    2991881     0         -1192 Layout Playground
    2991909     0         -1192 some BLocker
    2991937    -1         -1192 Properties
    2992034     0         -1120 Tracker shared icon cache
    2992041     0          1120 some BLocker
    2992053     0          1192 BMessageQueue Lock
    2992211     0          1120 PObjectBroker
